### ISSUE TITLE
Support html emails

### ISSUE THREAD

**Issue by bojingo** [TanukiSharp/MinimalSendGrid#1]
I really like the simplicity of this library, but it would be nice to provide the email body in either HTML or plain text (or both?).

**Comment by TanukiSharp** [comment]
Thanks bojingo

Yes the SendGrid API allows to send both plain text and HTML at once, though I would like to make some tests before in order to understand what happens on the recipient's side.

Does he/she see both stacked ?
Does the email client software automatically selects one to display and discard the other ?

As said in the description, this library is mostly intended for server side scenarios, so HTML is of low interest in my opinion. However, I admit it could be useful to send information with color, such as green for OK and red for errors, and I also do understand that some people may want to use it in client side scenarios to send to more beautiful content.

I'll try to find time to test, and eventually implement this feature.

**Comment by TanukiSharp** [comment]
Hello bojingo

HTML support has been added, with readme updated at commit 55f252caa8d9f1a4439b551e1bd0b7bc0cd9df53.

After performing a few tests, when adding several different types of body, they both appear in the email source, but the mail client only displays one. I've tested with gmail, and it only displays the HTML part if available, and falls back to plain text otherwise.

So I implemented it to offer the possibility to add several bodies (how can more, can less after all). This introduced a small breaking change in the API of the `MessageBuilder` class, where the method `SetBody` has been renamed to `AddBody`. Also, there is now a new type named `MessageBody`.

I let you close this issue once you could confirm the feature is satisfying.

Thanks.

**Comment by bojingo** [comment]
Works great, thanks!
